// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialMediaPlatform.Data;

#nullable disable

namespace SocialMediaPlatform.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20241006103814_FixingPostRelationShip")]
    partial class FixingPostRelationShip
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocialMediaPlatform.Models.Creator", b =>
                {
                    b.Property<int>("CreatorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CreatorID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Followers")
                        .HasColumnType("int");

                    b.Property<int>("Following")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPost")
                        .HasColumnType("int");

                    b.Property<string>("PredictionImage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserDetailsID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CreatorID");

                    b.HasIndex("UserDetailsID")
                        .IsUnique();

                    b.ToTable("Creators");
                });

            modelBuilder.Entity("SocialMediaPlatform.Models.Photo", b =>
                {
                    b.Property<int>("PhotoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoID"));

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PostID")
                        .HasColumnType("int");

                    b.HasKey("PhotoID");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("SocialMediaPlatform.Models.Post", b =>
                {
                    b.Property<int>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<int?>("PhotoID")
                        .HasColumnType("int");

                    b.Property<int>("Reactions")
                        .HasColumnType("int");

                    b.Property<int?>("VideoID")
                        .HasColumnType("int");

                    b.HasKey("PostID");

                    b.HasIndex("CreatorID");

                    b.HasIndex("PhotoID")
                        .IsUnique()
                        .HasFilter("[PhotoID] IS NOT NULL");

                    b.HasIndex("VideoID")
                        .IsUnique()
                        .HasFilter("[VideoID] IS NOT NULL");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("SocialMediaPlatform.Models.UserDetails", b =>
                {
                    b.Property<int>("UserDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserDetailsID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserDetailsID");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("SocialMediaPlatform.Models.Video", b =>
                {
                    b.Property<int>("VideoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideoID"));

                    b.Property<int?>("PostID")
                        .HasColumnType("int");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("VideoID");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("SocialMediaPlatform.Models.Creator", b =>
                {
                    b.HasOne("SocialMediaPlatform.Models.UserDetails", "UserDetails")
                        .WithOne()
                        .HasForeignKey("SocialMediaPlatform.Models.Creator", "UserDetailsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDetails");
                });

            modelBuilder.Entity("SocialMediaPlatform.Models.Post", b =>
                {
                    b.HasOne("SocialMediaPlatform.Models.Creator", "Creator")
                        .WithMany("Posts")
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaPlatform.Models.Photo", "Photo")
                        .WithOne("Post")
                        .HasForeignKey("SocialMediaPlatform.Models.Post", "PhotoID");

                    b.HasOne("SocialMediaPlatform.Models.Video", "Video")
                        .WithOne("Post")
                        .HasForeignKey("SocialMediaPlatform.Models.Post", "VideoID");

                    b.Navigation("Creator");

                    b.Navigation("Photo");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("SocialMediaPlatform.Models.Creator", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("SocialMediaPlatform.Models.Photo", b =>
                {
                    b.Navigation("Post");
                });

            modelBuilder.Entity("SocialMediaPlatform.Models.Video", b =>
                {
                    b.Navigation("Post");
                });
#pragma warning restore 612, 618
        }
    }
}
